# Generated by Django 2.0.3 on 2018-03-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
